version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.18
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GDT9MbJUTFHpyJyeS2JxzgkpYTjnrU8v
    command: mongod --port ${MONGODB_PORT:-27017}
    ports:
      - 27017

  chatgpt-telegram:
    container_name: chatgpt
    command: python3 -m bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
# check https://gg.resisto.rodeo/yo/chatgpTG/src/branch/main/docs/variables for more
      - MONGODB_HOST=mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=GDT9MbJUTFHpyJyeS2JxzgkpYTjnrU8v

      - TELEGRAM_TOKEN=6101.....

#opcional    volumes:
#      - /ruta-fuera-del-docker/mi-configuracion:/config
