version: "3"
#i deploy like this
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.18
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GDT9MbJUTFHpyJyeS2JxzgkpYTjnrU8v
    command: mongod --port ${MONGODB_PORT:-27017}
    ports:
      - 27017

  chatgpt-telegram:
    container_name: chatgpt
    command: python3 -m bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AUTO_LANG=es
      - WITHOUT_MONGODB=False
      - MONGODB_HOST=mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=GDT9MbJUTFHpyJyeS2JxzgkpYTjnrU8v

      - TELEGRAM_TOKEN=6101.....
      - USER_WHITELIST=
      - CHAT_WHITELIST=

      - DIALOG_TIMEOUT=7200
      - TIMEOUT_ASK=True
      - OUTPUT_IMAGES=4
      - FEATURE_IMAGE_READ=True
      - FEATURE_IMAGE_GENERATION=True
      - GENERATED_IMAGE_EXPIRATION_MINUTES=5

      - FEATURE_TRANSCRIPTION=True
      - FEATURE_BROWSING=True
      - FEATURE_DOCUMENT_READ=True
      - FEATURE_URL_READ=True
      - FEATURE_FUNCTION_CALLS=True
      - MAX_ITEMS_PER_PAGE=10
      - MAX_COLUMNS_PER_PAGE=2
      #- API_TUNNEL=http://my:proxy
      - AUDIO_MAX_MB=20
      - DOC_MAX_MB=10
      - URL_MAX_MB=5
      - PDF_PAGE_LIMIT=25

      - STREAM_ANSWERS=True
      - REQUEST_TIMEOUT=7
      - REQUEST_MAX_RETRIES=3

      - GPT4FREE_BING_U_COOKIE=1ic.......
      - GPT4FREE_CHATGPT_SESSION_TOKEN=eyJhb....

#opcional    volumes:
#      - /ruta-fuera-del-docker/mi-configuracion:/config
